CREATE TABLE IF NOT EXISTS t_chat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    summary VARCHAR(255) NOT NULL,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS t_chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id VARCHAR(80) NOT NULL,
    role VARCHAR(30) NOT NULL,
    content TEXT NOT NULL,
    reasoning_content TEXT,
    create_time TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_chat_message_chat_id ON t_chat_message(chat_id, create_time);

CREATE TABLE IF NOT EXISTS t_ai_customer_service_md_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    md5 VARCHAR(64),
    original_file_name VARCHAR(255) NOT NULL,
    storage_path VARCHAR(1000) NOT NULL,
    file_size BIGINT NOT NULL,
    status INT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_md_storage_md5 ON t_ai_customer_service_md_storage(md5);

CREATE TABLE IF NOT EXISTS t_ai_customer_service_file_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_md5 VARCHAR(64) NOT NULL UNIQUE,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(1000),
    file_size BIGINT NOT NULL DEFAULT 0,
    total_chunks INT NOT NULL,
    uploaded_chunks INT NOT NULL DEFAULT 0,
    status INT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_file_storage_status ON t_ai_customer_service_file_storage(status);

CREATE TABLE IF NOT EXISTS t_file_chunk_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_md5 VARCHAR(64) NOT NULL,
    chunk_index INT NOT NULL,
    chunk_size BIGINT NOT NULL,
    storage_path VARCHAR(1000) NOT NULL,
    create_time TIMESTAMP NOT NULL,
    UNIQUE(file_md5, chunk_index)
);
