<template>
  <Layout @home="router.push('/')" @customer-service="router.push('/customer-service')" @lab="router.push('/lab')" @select-chat="id => router.push('/chat/' + id)" @new-chat="router.push('/')">
    <div class="h-full overflow-y-auto">
      <header class="border-b border-slate-200/70 bg-white px-6 py-5"><div class="flex items-center gap-2 text-sm font-semibold text-slate-800"><FlaskConical :size="17" class="text-[#4d6bfe]" />能力实验室</div><p class="mt-1 text-xs text-slate-400">直接运行 Spring AI 项目中的 Prompt、结构化输出、Advisor 和 Agent 实例</p></header>
      <main class="mx-auto grid max-w-5xl gap-4 px-5 py-6 lg:grid-cols-2">
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center gap-2 text-sm font-semibold text-slate-800"><TextCursorInput :size="16" class="text-indigo-500" />PromptTemplate</div><div class="mt-4 flex gap-2"><input v-model="topic" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-indigo-400" /><button @click="runPrompt" :disabled="busy" class="rounded-lg bg-[#4d6bfe] px-3 py-2 text-xs text-white disabled:opacity-50">运行</button></div><pre class="mt-4 max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-xs leading-6 text-slate-600">{{ promptResult || '等待运行' }}</pre></section>
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center gap-2 text-sm font-semibold text-slate-800"><Braces :size="16" class="text-emerald-500" />结构化输出</div><div class="mt-4 flex gap-2"><select v-model="structuredType" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none"><option value="actor">演员作品</option><option value="language">语言信息</option><option value="cities">城市列表</option></select><button @click="runStructured" :disabled="busy" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs text-white disabled:opacity-50">运行</button></div><pre class="mt-4 max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-xs leading-6 text-slate-600">{{ structuredResult || '等待运行' }}</pre></section>
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center gap-2 text-sm font-semibold text-slate-800"><Search :size="16" class="text-amber-500" />联网搜索 Advisor</div><div class="mt-4 flex gap-2"><input v-model="advisorQuestion" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-amber-400" /><button @click="runAdvisor" :disabled="busy" class="rounded-lg bg-amber-500 px-3 py-2 text-xs text-white disabled:opacity-50">流式运行</button></div><pre class="mt-4 max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-xs leading-6 text-slate-600">{{ advisorResult || '等待运行' }}</pre></section>
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center gap-2 text-sm font-semibold text-slate-800"><Gauge :size="16" class="text-rose-500" />知识库客服 Agent Loop</div><div class="mt-4 flex gap-2"><input v-model="agentQuestion" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-rose-400" /><button @click="runAgent" :disabled="busy" class="rounded-lg bg-rose-500 px-3 py-2 text-xs text-white disabled:opacity-50">基线对比</button></div><div v-if="agentResult" class="mt-4 grid grid-cols-2 gap-2 text-xs"><div v-for="item in metricItems" :key="item.key" class="rounded-lg bg-slate-50 px-3 py-2"><div class="text-slate-400">{{ item.label }}</div><div class="mt-1 font-semibold text-slate-700">{{ item.value }}</div></div></div><pre v-if="agentResult" class="mt-3 max-h-36 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-xs leading-6 text-slate-600">{{ agentResult.harness?.answer }}</pre></section>
      </main>
    </div>
  </Layout>
</template>
<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { FlaskConical, TextCursorInput, Braces, Search, Gauge } from 'lucide-vue-next'
import Layout from '@/layouts/Layout.vue'
import { api } from '@/services/api'
const router = useRouter(); const busy = ref(false); const topic = ref('Spring AI'); const promptResult = ref(''); const structuredType = ref('actor'); const structuredResult = ref(''); const advisorQuestion = ref('Spring AI 最新版本'); const advisorResult = ref(''); const agentQuestion = ref('如何接入 Ollama？'); const agentResult = ref(null)
async function runPrompt() { busy.value = true; try { promptResult.value = await api.promptTemplate(topic.value) } catch (e) { promptResult.value = e.message } finally { busy.value = false } }
async function runStructured() { busy.value = true; try { const result = structuredType.value === 'actor' ? await api.structuredActor() : structuredType.value === 'language' ? await api.structuredLanguage() : await api.structuredCities(); structuredResult.value = JSON.stringify(result, null, 2) } catch (e) { structuredResult.value = e.message } finally { busy.value = false } }
async function runAdvisor() { busy.value = true; advisorResult.value = ''; try { await api.streamAdvisor(advisorQuestion.value, { onChunk(chunk) { if (chunk.v) advisorResult.value += chunk.v; if (chunk.reasoning) advisorResult.value += chunk.reasoning } }) } catch (e) { advisorResult.value = e.message } finally { busy.value = false } }
async function runAgent() { busy.value = true; try { agentResult.value = await api.agentCompare(agentQuestion.value) } catch (e) { agentResult.value = { harness: { answer: e.message } } } finally { busy.value = false } }
const metricItems = computed(() => { const b = agentResult.value?.baseline?.metrics || {}; const h = agentResult.value?.harness?.metrics || {}; return [{ key: 'baseline', label: '基线耗时', value: b.totalMs == null ? '-' : `${b.totalMs} ms` }, { key: 'harness', label: 'Harness 耗时', value: h.totalMs == null ? '-' : `${h.totalMs} ms` }, { key: 'context', label: '知识库上下文', value: `${agentResult.value?.groundedContextChars ?? 0} 字符` }, { key: 'calls', label: '模型调用差值', value: agentResult.value?.modelCallDelta ?? '-' }] })
</script>
