<template>
  <Layout @home="router.push('/')" @customer-service="router.push('/customer-service')" @lab="router.push('/lab')" @select-chat="id => router.push('/chat/' + id)" @new-chat="router.push('/')">
    <div class="flex h-full flex-col">
      <header class="flex h-16 shrink-0 items-center justify-between border-b border-slate-200/70 bg-white px-6"><div><div class="text-sm font-semibold text-slate-800">智能客服</div><div class="text-xs text-slate-400">基于 Markdown 知识库的专属问答</div></div><button @click="showFiles = true; loadFiles()" class="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-600 hover:border-indigo-200 hover:text-indigo-600"><BookOpen :size="15" />知识库管理</button></header>
      <div ref="scroll" class="scroll-soft min-h-0 flex-1 overflow-y-auto"><div class="mx-auto max-w-3xl px-4 py-8 sm:px-8"><div v-if="!messages.length" class="py-20 text-center"><div class="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-indigo-50 text-indigo-500"><BookOpen :size="22" /></div><div class="mt-4 text-sm font-medium text-slate-700">向智答ai客服提问</div><div class="mt-1 text-xs text-slate-400">回答将依据已上传的 Markdown 问答文件</div></div><article v-for="(item,index) in messages" :key="index" class="mb-7 flex gap-3" :class="item.role === 'user' ? 'justify-end' : 'justify-start'"><div v-if="item.role !== 'user'" class="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-indigo-50 text-indigo-500"><BookOpen :size="16" /></div><div :class="item.role === 'user' ? 'bg-[#edf2ff]' : 'bg-white'" class="max-w-[84%] rounded-2xl px-4 py-3 text-[15px] leading-7 shadow-sm"><MarkdownRenderer v-if="item.role !== 'user'" :content="item.content" /><span v-else class="whitespace-pre-wrap">{{ item.content }}</span><LoadingSpinner v-if="item.role !== 'user' && index === messages.length - 1 && busy" /></div></article></div></div>
      <div class="shrink-0 border-t border-slate-200/70 bg-[#f7f9fc]/95 pt-3"><ChatInputBox placeholder="向知识库提问" :busy="busy" @send="sendMessage" /></div>
    </div>
      <a-drawer v-model:open="showFiles" title="Markdown 问答文件" width="min(680px, 100vw)"><div class="mb-4 flex items-center justify-between gap-3"><div class="flex min-w-0 flex-1 items-center gap-2"><input v-model="keyword" @keyup.enter="loadFiles" placeholder="按文件名查询" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-xs outline-none" /><button @click="loadFiles" class="rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-600">查询</button></div><label class="flex shrink-0 cursor-pointer items-center gap-2 rounded-lg bg-[#4d6bfe] px-3 py-2 text-xs text-white"><Upload :size="14" />上传<input type="file" accept=".md,.markdown" class="hidden" @change="upload" /></label></div><div class="mb-3 text-xs text-slate-400">共 {{ filesTotal }} 个文件</div><div class="space-y-2"><div v-for="file in files" :key="file.id" class="flex items-center justify-between rounded-xl border border-slate-200 p-3"><div class="flex min-w-0 items-center gap-3"><FileText :size="18" class="shrink-0 text-indigo-400" /><div class="min-w-0"><div class="truncate text-sm text-slate-700">{{ file.originalFileName }}</div><div class="text-xs text-slate-400">{{ file.fileSize }} · {{ file.status === 2 ? '已完成' : file.status === 1 ? '处理中' : file.status === 3 ? '失败' : '待处理' }}</div></div></div><div class="flex shrink-0 items-center gap-1"><button @click="editFile(file)" class="p-2 text-slate-400 hover:text-indigo-500" title="编辑"><Pencil :size="15" /></button><button @click="removeFile(file)" class="p-2 text-slate-400 hover:text-red-500" title="删除"><Trash2 :size="15" /></button></div></div><div v-if="!files.length" class="py-12 text-center text-xs text-slate-400">还没有上传问答文件</div></div><div class="my-5 border-t border-slate-200"></div><ChunkUploadPanel /></a-drawer>
  </Layout>
</template>
<script setup>
import { ref, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import { BookOpen, Upload, FileText, Trash2, Pencil } from 'lucide-vue-next'
import Layout from '@/layouts/Layout.vue'
import ChatInputBox from '@/components/ChatInputBox.vue'
import ChunkUploadPanel from '@/components/ChunkUploadPanel.vue'
import MarkdownRenderer from '@/components/MarkdownRenderer.vue'
import LoadingSpinner from '@/components/LoadingSpinner.vue'
import { api } from '@/services/api'
const router = useRouter(); const messages = ref([]); const busy = ref(false); const scroll = ref(null); const showFiles = ref(false); const files = ref([]); const filesTotal = ref(0); const keyword = ref('')
function bottom() { nextTick(() => { if (scroll.value) scroll.value.scrollTop = scroll.value.scrollHeight }) }
async function sendMessage(payload) { if (!payload?.message || busy.value) return; const message = payload.message; messages.value.push({ role: 'user', content: message }); messages.value.push({ role: 'assistant', content: '' }); busy.value = true; bottom(); try { await api.streamCustomerChat({ message, modelName: payload.selectedModel?.name, temperature: .7 }, { onChunk(chunk) { const last = messages.value.at(-1); if (chunk.v) last.content += chunk.v; if (chunk.done) busy.value = false; bottom() }, onClose() { busy.value = false }, onError(error) { throw error } }) } catch (error) { messages.value.at(-1).content = `请求失败：${error.message}` } finally { busy.value = false } }
async function loadFiles() { try { const result = await api.files(1, 20, keyword.value); files.value = result.data || []; filesTotal.value = result.total || files.value.length } catch {} }
async function upload(event) { const file = event.target.files?.[0]; if (!file) return; try { await api.uploadKnowledge(file); await loadFiles() } catch (error) { window.alert(error.message) } event.target.value = '' }
async function removeFile(file) { if (!window.confirm(`删除 ${file.originalFileName}？`)) return; await api.deleteFile(file.id); await loadFiles() }
async function editFile(file) { const fileName = window.prompt('文件名', file.originalFileName); if (!fileName?.trim()) return; const remark = window.prompt('备注', file.remark || '') ?? ''; try { await api.updateFile(file.id, fileName.trim(), remark); await loadFiles() } catch (error) { window.alert(error.message) } }
</script>
